/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vietnamobile.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.vietnamobile.model.VnmArticleReportEntry;
import com.vietnamobile.model.VnmArticleReportEntryModel;
import com.vietnamobile.model.VnmArticleReportEntrySoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the VnmArticleReportEntry service. Represents a row in the &quot;iskools_VnmArticleReportEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vietnamobile.model.VnmArticleReportEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VnmArticleReportEntryImpl}.
 * </p>
 *
 * @author duymb
 * @see VnmArticleReportEntryImpl
 * @see com.vietnamobile.model.VnmArticleReportEntry
 * @see com.vietnamobile.model.VnmArticleReportEntryModel
 * @generated
 */
@JSON(strict = true)
public class VnmArticleReportEntryModelImpl extends BaseModelImpl<VnmArticleReportEntry>
	implements VnmArticleReportEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vnm article report entry model instance should use the {@link com.vietnamobile.model.VnmArticleReportEntry} interface instead.
	 */
	public static final String TABLE_NAME = "iskools_VnmArticleReportEntry";
	public static final Object[][] TABLE_COLUMNS = {
			{ "vnmArticleReportEntryId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "articleId", Types.VARCHAR },
			{ "version", Types.DOUBLE },
			{ "title", Types.VARCHAR },
			{ "action", Types.VARCHAR },
			{ "status", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table iskools_VnmArticleReportEntry (vnmArticleReportEntryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,articleId VARCHAR(75) null,version DOUBLE,title VARCHAR(75) null,action VARCHAR(75) null,status INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table iskools_VnmArticleReportEntry";
	public static final String ORDER_BY_JPQL = " ORDER BY vnmArticleReportEntry.vnmArticleReportEntryId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY iskools_VnmArticleReportEntry.vnmArticleReportEntryId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vietnamobile.model.VnmArticleReportEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vietnamobile.model.VnmArticleReportEntry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VnmArticleReportEntry toModel(
		VnmArticleReportEntrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		VnmArticleReportEntry model = new VnmArticleReportEntryImpl();

		model.setVnmArticleReportEntryId(soapModel.getVnmArticleReportEntryId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setArticleId(soapModel.getArticleId());
		model.setVersion(soapModel.getVersion());
		model.setTitle(soapModel.getTitle());
		model.setAction(soapModel.getAction());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VnmArticleReportEntry> toModels(
		VnmArticleReportEntrySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<VnmArticleReportEntry> models = new ArrayList<VnmArticleReportEntry>(soapModels.length);

		for (VnmArticleReportEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vietnamobile.model.VnmArticleReportEntry"));

	public VnmArticleReportEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _vnmArticleReportEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVnmArticleReportEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _vnmArticleReportEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VnmArticleReportEntry.class;
	}

	@Override
	public String getModelClassName() {
		return VnmArticleReportEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("vnmArticleReportEntryId", getVnmArticleReportEntryId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("articleId", getArticleId());
		attributes.put("version", getVersion());
		attributes.put("title", getTitle());
		attributes.put("action", getAction());
		attributes.put("status", getStatus());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long vnmArticleReportEntryId = (Long)attributes.get(
				"vnmArticleReportEntryId");

		if (vnmArticleReportEntryId != null) {
			setVnmArticleReportEntryId(vnmArticleReportEntryId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String articleId = (String)attributes.get("articleId");

		if (articleId != null) {
			setArticleId(articleId);
		}

		Double version = (Double)attributes.get("version");

		if (version != null) {
			setVersion(version);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		String action = (String)attributes.get("action");

		if (action != null) {
			setAction(action);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@JSON
	@Override
	public long getVnmArticleReportEntryId() {
		return _vnmArticleReportEntryId;
	}

	@Override
	public void setVnmArticleReportEntryId(long vnmArticleReportEntryId) {
		_vnmArticleReportEntryId = vnmArticleReportEntryId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getArticleId() {
		if (_articleId == null) {
			return StringPool.BLANK;
		}
		else {
			return _articleId;
		}
	}

	@Override
	public void setArticleId(String articleId) {
		_articleId = articleId;
	}

	@JSON
	@Override
	public double getVersion() {
		return _version;
	}

	@Override
	public void setVersion(double version) {
		_version = version;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@JSON
	@Override
	public String getAction() {
		if (_action == null) {
			return StringPool.BLANK;
		}
		else {
			return _action;
		}
	}

	@Override
	public void setAction(String action) {
		_action = action;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			VnmArticleReportEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VnmArticleReportEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VnmArticleReportEntry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VnmArticleReportEntryImpl vnmArticleReportEntryImpl = new VnmArticleReportEntryImpl();

		vnmArticleReportEntryImpl.setVnmArticleReportEntryId(getVnmArticleReportEntryId());
		vnmArticleReportEntryImpl.setGroupId(getGroupId());
		vnmArticleReportEntryImpl.setCompanyId(getCompanyId());
		vnmArticleReportEntryImpl.setUserId(getUserId());
		vnmArticleReportEntryImpl.setUserName(getUserName());
		vnmArticleReportEntryImpl.setCreateDate(getCreateDate());
		vnmArticleReportEntryImpl.setModifiedDate(getModifiedDate());
		vnmArticleReportEntryImpl.setArticleId(getArticleId());
		vnmArticleReportEntryImpl.setVersion(getVersion());
		vnmArticleReportEntryImpl.setTitle(getTitle());
		vnmArticleReportEntryImpl.setAction(getAction());
		vnmArticleReportEntryImpl.setStatus(getStatus());

		vnmArticleReportEntryImpl.resetOriginalValues();

		return vnmArticleReportEntryImpl;
	}

	@Override
	public int compareTo(VnmArticleReportEntry vnmArticleReportEntry) {
		long primaryKey = vnmArticleReportEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VnmArticleReportEntry)) {
			return false;
		}

		VnmArticleReportEntry vnmArticleReportEntry = (VnmArticleReportEntry)obj;

		long primaryKey = vnmArticleReportEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<VnmArticleReportEntry> toCacheModel() {
		VnmArticleReportEntryCacheModel vnmArticleReportEntryCacheModel = new VnmArticleReportEntryCacheModel();

		vnmArticleReportEntryCacheModel.vnmArticleReportEntryId = getVnmArticleReportEntryId();

		vnmArticleReportEntryCacheModel.groupId = getGroupId();

		vnmArticleReportEntryCacheModel.companyId = getCompanyId();

		vnmArticleReportEntryCacheModel.userId = getUserId();

		vnmArticleReportEntryCacheModel.userName = getUserName();

		String userName = vnmArticleReportEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			vnmArticleReportEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			vnmArticleReportEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			vnmArticleReportEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			vnmArticleReportEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			vnmArticleReportEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		vnmArticleReportEntryCacheModel.articleId = getArticleId();

		String articleId = vnmArticleReportEntryCacheModel.articleId;

		if ((articleId != null) && (articleId.length() == 0)) {
			vnmArticleReportEntryCacheModel.articleId = null;
		}

		vnmArticleReportEntryCacheModel.version = getVersion();

		vnmArticleReportEntryCacheModel.title = getTitle();

		String title = vnmArticleReportEntryCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			vnmArticleReportEntryCacheModel.title = null;
		}

		vnmArticleReportEntryCacheModel.action = getAction();

		String action = vnmArticleReportEntryCacheModel.action;

		if ((action != null) && (action.length() == 0)) {
			vnmArticleReportEntryCacheModel.action = null;
		}

		vnmArticleReportEntryCacheModel.status = getStatus();

		return vnmArticleReportEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{vnmArticleReportEntryId=");
		sb.append(getVnmArticleReportEntryId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", articleId=");
		sb.append(getArticleId());
		sb.append(", version=");
		sb.append(getVersion());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", action=");
		sb.append(getAction());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.vietnamobile.model.VnmArticleReportEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>vnmArticleReportEntryId</column-name><column-value><![CDATA[");
		sb.append(getVnmArticleReportEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>articleId</column-name><column-value><![CDATA[");
		sb.append(getArticleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>version</column-name><column-value><![CDATA[");
		sb.append(getVersion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>action</column-name><column-value><![CDATA[");
		sb.append(getAction());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = VnmArticleReportEntry.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			VnmArticleReportEntry.class
		};
	private long _vnmArticleReportEntryId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _articleId;
	private double _version;
	private String _title;
	private String _action;
	private int _status;
	private VnmArticleReportEntry _escapedModel;
}