/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vietnamobile.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the OnlinetestResultEntry service. Represents a row in the &quot;iskools_OnlinetestResultEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vietnamobile.model.impl.OnlinetestResultEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vietnamobile.model.impl.OnlinetestResultEntryImpl}.
 * </p>
 *
 * @author duymb
 * @see OnlinetestResultEntry
 * @see com.vietnamobile.model.impl.OnlinetestResultEntryImpl
 * @see com.vietnamobile.model.impl.OnlinetestResultEntryModelImpl
 * @generated
 */
public interface OnlinetestResultEntryModel extends BaseModel<OnlinetestResultEntry>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a onlinetest result entry model instance should use the {@link OnlinetestResultEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this onlinetest result entry.
	 *
	 * @return the primary key of this onlinetest result entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this onlinetest result entry.
	 *
	 * @param primaryKey the primary key of this onlinetest result entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the onlinetest result entry ID of this onlinetest result entry.
	 *
	 * @return the onlinetest result entry ID of this onlinetest result entry
	 */
	public long getOnlinetestResultEntryId();

	/**
	 * Sets the onlinetest result entry ID of this onlinetest result entry.
	 *
	 * @param onlinetestResultEntryId the onlinetest result entry ID of this onlinetest result entry
	 */
	public void setOnlinetestResultEntryId(long onlinetestResultEntryId);

	/**
	 * Returns the group ID of this onlinetest result entry.
	 *
	 * @return the group ID of this onlinetest result entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this onlinetest result entry.
	 *
	 * @param groupId the group ID of this onlinetest result entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this onlinetest result entry.
	 *
	 * @return the company ID of this onlinetest result entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this onlinetest result entry.
	 *
	 * @param companyId the company ID of this onlinetest result entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this onlinetest result entry.
	 *
	 * @return the user ID of this onlinetest result entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this onlinetest result entry.
	 *
	 * @param userId the user ID of this onlinetest result entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this onlinetest result entry.
	 *
	 * @return the user uuid of this onlinetest result entry
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this onlinetest result entry.
	 *
	 * @param userUuid the user uuid of this onlinetest result entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this onlinetest result entry.
	 *
	 * @return the user name of this onlinetest result entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this onlinetest result entry.
	 *
	 * @param userName the user name of this onlinetest result entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this onlinetest result entry.
	 *
	 * @return the create date of this onlinetest result entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this onlinetest result entry.
	 *
	 * @param createDate the create date of this onlinetest result entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this onlinetest result entry.
	 *
	 * @return the modified date of this onlinetest result entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this onlinetest result entry.
	 *
	 * @param modifiedDate the modified date of this onlinetest result entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the online test entry ID of this onlinetest result entry.
	 *
	 * @return the online test entry ID of this onlinetest result entry
	 */
	public long getOnlineTestEntryId();

	/**
	 * Sets the online test entry ID of this onlinetest result entry.
	 *
	 * @param onlineTestEntryId the online test entry ID of this onlinetest result entry
	 */
	public void setOnlineTestEntryId(long onlineTestEntryId);

	/**
	 * Returns the score of this onlinetest result entry.
	 *
	 * @return the score of this onlinetest result entry
	 */
	public double getScore();

	/**
	 * Sets the score of this onlinetest result entry.
	 *
	 * @param score the score of this onlinetest result entry
	 */
	public void setScore(double score);

	/**
	 * Returns the answer selected of this onlinetest result entry.
	 *
	 * @return the answer selected of this onlinetest result entry
	 */
	@AutoEscape
	public String getAnswerSelected();

	/**
	 * Sets the answer selected of this onlinetest result entry.
	 *
	 * @param answerSelected the answer selected of this onlinetest result entry
	 */
	public void setAnswerSelected(String answerSelected);

	/**
	 * Returns the number of wrong answer of this onlinetest result entry.
	 *
	 * @return the number of wrong answer of this onlinetest result entry
	 */
	public int getNumberOfWrongAnswer();

	/**
	 * Sets the number of wrong answer of this onlinetest result entry.
	 *
	 * @param numberOfWrongAnswer the number of wrong answer of this onlinetest result entry
	 */
	public void setNumberOfWrongAnswer(int numberOfWrongAnswer);

	/**
	 * Returns the time remaining of this onlinetest result entry.
	 *
	 * @return the time remaining of this onlinetest result entry
	 */
	public int getTimeRemaining();

	/**
	 * Sets the time remaining of this onlinetest result entry.
	 *
	 * @param timeRemaining the time remaining of this onlinetest result entry
	 */
	public void setTimeRemaining(int timeRemaining);

	/**
	 * Returns the exam type of this onlinetest result entry.
	 *
	 * @return the exam type of this onlinetest result entry
	 */
	@AutoEscape
	public String getExamType();

	/**
	 * Sets the exam type of this onlinetest result entry.
	 *
	 * @param examType the exam type of this onlinetest result entry
	 */
	public void setExamType(String examType);

	/**
	 * Returns the question IDs of this onlinetest result entry.
	 *
	 * @return the question IDs of this onlinetest result entry
	 */
	@AutoEscape
	public String getQuestionIds();

	/**
	 * Sets the question IDs of this onlinetest result entry.
	 *
	 * @param questionIds the question IDs of this onlinetest result entry
	 */
	public void setQuestionIds(String questionIds);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.vietnamobile.model.OnlinetestResultEntry onlinetestResultEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.vietnamobile.model.OnlinetestResultEntry> toCacheModel();

	@Override
	public com.vietnamobile.model.OnlinetestResultEntry toEscapedModel();

	@Override
	public com.vietnamobile.model.OnlinetestResultEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}