/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vietnamobile.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the OnlinetestEntry service. Represents a row in the &quot;iskools_OnlinetestEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vietnamobile.model.impl.OnlinetestEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vietnamobile.model.impl.OnlinetestEntryImpl}.
 * </p>
 *
 * @author duymb
 * @see OnlinetestEntry
 * @see com.vietnamobile.model.impl.OnlinetestEntryImpl
 * @see com.vietnamobile.model.impl.OnlinetestEntryModelImpl
 * @generated
 */
public interface OnlinetestEntryModel extends BaseModel<OnlinetestEntry>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a onlinetest entry model instance should use the {@link OnlinetestEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this onlinetest entry.
	 *
	 * @return the primary key of this onlinetest entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this onlinetest entry.
	 *
	 * @param primaryKey the primary key of this onlinetest entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the onlinetest entry ID of this onlinetest entry.
	 *
	 * @return the onlinetest entry ID of this onlinetest entry
	 */
	public long getOnlinetestEntryId();

	/**
	 * Sets the onlinetest entry ID of this onlinetest entry.
	 *
	 * @param onlinetestEntryId the onlinetest entry ID of this onlinetest entry
	 */
	public void setOnlinetestEntryId(long onlinetestEntryId);

	/**
	 * Returns the group ID of this onlinetest entry.
	 *
	 * @return the group ID of this onlinetest entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this onlinetest entry.
	 *
	 * @param groupId the group ID of this onlinetest entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this onlinetest entry.
	 *
	 * @return the company ID of this onlinetest entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this onlinetest entry.
	 *
	 * @param companyId the company ID of this onlinetest entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this onlinetest entry.
	 *
	 * @return the user ID of this onlinetest entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this onlinetest entry.
	 *
	 * @param userId the user ID of this onlinetest entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this onlinetest entry.
	 *
	 * @return the user uuid of this onlinetest entry
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this onlinetest entry.
	 *
	 * @param userUuid the user uuid of this onlinetest entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this onlinetest entry.
	 *
	 * @return the user name of this onlinetest entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this onlinetest entry.
	 *
	 * @param userName the user name of this onlinetest entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this onlinetest entry.
	 *
	 * @return the create date of this onlinetest entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this onlinetest entry.
	 *
	 * @param createDate the create date of this onlinetest entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this onlinetest entry.
	 *
	 * @return the modified date of this onlinetest entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this onlinetest entry.
	 *
	 * @param modifiedDate the modified date of this onlinetest entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the question ID of this onlinetest entry.
	 *
	 * @return the question ID of this onlinetest entry
	 */
	@AutoEscape
	public String getQuestionId();

	/**
	 * Sets the question ID of this onlinetest entry.
	 *
	 * @param questionId the question ID of this onlinetest entry
	 */
	public void setQuestionId(String questionId);

	/**
	 * Returns the test start time of this onlinetest entry.
	 *
	 * @return the test start time of this onlinetest entry
	 */
	public Date getTestStartTime();

	/**
	 * Sets the test start time of this onlinetest entry.
	 *
	 * @param testStartTime the test start time of this onlinetest entry
	 */
	public void setTestStartTime(Date testStartTime);

	/**
	 * Returns the test end time of this onlinetest entry.
	 *
	 * @return the test end time of this onlinetest entry
	 */
	public Date getTestEndTime();

	/**
	 * Sets the test end time of this onlinetest entry.
	 *
	 * @param testEndTime the test end time of this onlinetest entry
	 */
	public void setTestEndTime(Date testEndTime);

	/**
	 * Returns the duration of this onlinetest entry.
	 *
	 * @return the duration of this onlinetest entry
	 */
	public int getDuration();

	/**
	 * Sets the duration of this onlinetest entry.
	 *
	 * @param duration the duration of this onlinetest entry
	 */
	public void setDuration(int duration);

	/**
	 * Returns the number of questions of this onlinetest entry.
	 *
	 * @return the number of questions of this onlinetest entry
	 */
	public int getNumberOfQuestions();

	/**
	 * Sets the number of questions of this onlinetest entry.
	 *
	 * @param numberOfQuestions the number of questions of this onlinetest entry
	 */
	public void setNumberOfQuestions(int numberOfQuestions);

	/**
	 * Returns the title of this onlinetest entry.
	 *
	 * @return the title of this onlinetest entry
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this onlinetest entry.
	 *
	 * @param title the title of this onlinetest entry
	 */
	public void setTitle(String title);

	/**
	 * Returns the point of this onlinetest entry.
	 *
	 * @return the point of this onlinetest entry
	 */
	public int getPoint();

	/**
	 * Sets the point of this onlinetest entry.
	 *
	 * @param point the point of this onlinetest entry
	 */
	public void setPoint(int point);

	/**
	 * Returns the status of this onlinetest entry.
	 *
	 * @return the status of this onlinetest entry
	 */
	public int getStatus();

	/**
	 * Sets the status of this onlinetest entry.
	 *
	 * @param status the status of this onlinetest entry
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.vietnamobile.model.OnlinetestEntry onlinetestEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.vietnamobile.model.OnlinetestEntry> toCacheModel();

	@Override
	public com.vietnamobile.model.OnlinetestEntry toEscapedModel();

	@Override
	public com.vietnamobile.model.OnlinetestEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}