/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vietnamobile.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the QuestionEntry service. Represents a row in the &quot;iskools_QuestionEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vietnamobile.model.impl.QuestionEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vietnamobile.model.impl.QuestionEntryImpl}.
 * </p>
 *
 * @author duymb
 * @see QuestionEntry
 * @see com.vietnamobile.model.impl.QuestionEntryImpl
 * @see com.vietnamobile.model.impl.QuestionEntryModelImpl
 * @generated
 */
public interface QuestionEntryModel extends BaseModel<QuestionEntry>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a question entry model instance should use the {@link QuestionEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this question entry.
	 *
	 * @return the primary key of this question entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this question entry.
	 *
	 * @param primaryKey the primary key of this question entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the question entry ID of this question entry.
	 *
	 * @return the question entry ID of this question entry
	 */
	public long getQuestionEntryId();

	/**
	 * Sets the question entry ID of this question entry.
	 *
	 * @param questionEntryId the question entry ID of this question entry
	 */
	public void setQuestionEntryId(long questionEntryId);

	/**
	 * Returns the group ID of this question entry.
	 *
	 * @return the group ID of this question entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this question entry.
	 *
	 * @param groupId the group ID of this question entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this question entry.
	 *
	 * @return the company ID of this question entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this question entry.
	 *
	 * @param companyId the company ID of this question entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this question entry.
	 *
	 * @return the user ID of this question entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this question entry.
	 *
	 * @param userId the user ID of this question entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this question entry.
	 *
	 * @return the user uuid of this question entry
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this question entry.
	 *
	 * @param userUuid the user uuid of this question entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this question entry.
	 *
	 * @return the user name of this question entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this question entry.
	 *
	 * @param userName the user name of this question entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this question entry.
	 *
	 * @return the create date of this question entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this question entry.
	 *
	 * @param createDate the create date of this question entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this question entry.
	 *
	 * @return the modified date of this question entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this question entry.
	 *
	 * @param modifiedDate the modified date of this question entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the subject of this question entry.
	 *
	 * @return the subject of this question entry
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this question entry.
	 *
	 * @param subject the subject of this question entry
	 */
	public void setSubject(String subject);

	/**
	 * Returns the level question of this question entry.
	 *
	 * @return the level question of this question entry
	 */
	public double getLevelQuestion();

	/**
	 * Sets the level question of this question entry.
	 *
	 * @param levelQuestion the level question of this question entry
	 */
	public void setLevelQuestion(double levelQuestion);

	/**
	 * Returns the answer of this question entry.
	 *
	 * @return the answer of this question entry
	 */
	@AutoEscape
	public String getAnswer();

	/**
	 * Sets the answer of this question entry.
	 *
	 * @param answer the answer of this question entry
	 */
	public void setAnswer(String answer);

	/**
	 * Returns the score of this question entry.
	 *
	 * @return the score of this question entry
	 */
	public double getScore();

	/**
	 * Sets the score of this question entry.
	 *
	 * @param score the score of this question entry
	 */
	public void setScore(double score);

	/**
	 * Returns the question content of this question entry.
	 *
	 * @return the question content of this question entry
	 */
	@AutoEscape
	public String getQuestionContent();

	/**
	 * Sets the question content of this question entry.
	 *
	 * @param questionContent the question content of this question entry
	 */
	public void setQuestionContent(String questionContent);

	/**
	 * Returns the a of this question entry.
	 *
	 * @return the a of this question entry
	 */
	@AutoEscape
	public String getA();

	/**
	 * Sets the a of this question entry.
	 *
	 * @param a the a of this question entry
	 */
	public void setA(String a);

	/**
	 * Returns the b of this question entry.
	 *
	 * @return the b of this question entry
	 */
	@AutoEscape
	public String getB();

	/**
	 * Sets the b of this question entry.
	 *
	 * @param b the b of this question entry
	 */
	public void setB(String b);

	/**
	 * Returns the c of this question entry.
	 *
	 * @return the c of this question entry
	 */
	@AutoEscape
	public String getC();

	/**
	 * Sets the c of this question entry.
	 *
	 * @param c the c of this question entry
	 */
	public void setC(String c);

	/**
	 * Returns the d of this question entry.
	 *
	 * @return the d of this question entry
	 */
	@AutoEscape
	public String getD();

	/**
	 * Sets the d of this question entry.
	 *
	 * @param d the d of this question entry
	 */
	public void setD(String d);

	/**
	 * Returns the title of this question entry.
	 *
	 * @return the title of this question entry
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this question entry.
	 *
	 * @param title the title of this question entry
	 */
	public void setTitle(String title);

	/**
	 * Returns the selection1 of this question entry.
	 *
	 * @return the selection1 of this question entry
	 */
	@AutoEscape
	public String getSelection1();

	/**
	 * Sets the selection1 of this question entry.
	 *
	 * @param selection1 the selection1 of this question entry
	 */
	public void setSelection1(String selection1);

	/**
	 * Returns the selection2 of this question entry.
	 *
	 * @return the selection2 of this question entry
	 */
	@AutoEscape
	public String getSelection2();

	/**
	 * Sets the selection2 of this question entry.
	 *
	 * @param selection2 the selection2 of this question entry
	 */
	public void setSelection2(String selection2);

	/**
	 * Returns the selection3 of this question entry.
	 *
	 * @return the selection3 of this question entry
	 */
	@AutoEscape
	public String getSelection3();

	/**
	 * Sets the selection3 of this question entry.
	 *
	 * @param selection3 the selection3 of this question entry
	 */
	public void setSelection3(String selection3);

	/**
	 * Returns the selection4 of this question entry.
	 *
	 * @return the selection4 of this question entry
	 */
	@AutoEscape
	public String getSelection4();

	/**
	 * Sets the selection4 of this question entry.
	 *
	 * @param selection4 the selection4 of this question entry
	 */
	public void setSelection4(String selection4);

	/**
	 * Returns the type exam of this question entry.
	 *
	 * @return the type exam of this question entry
	 */
	@AutoEscape
	public String getTypeExam();

	/**
	 * Sets the type exam of this question entry.
	 *
	 * @param typeExam the type exam of this question entry
	 */
	public void setTypeExam(String typeExam);

	/**
	 * Returns the in exam of this question entry.
	 *
	 * @return the in exam of this question entry
	 */
	public int getInExam();

	/**
	 * Sets the in exam of this question entry.
	 *
	 * @param inExam the in exam of this question entry
	 */
	public void setInExam(int inExam);

	/**
	 * Returns the status of this question entry.
	 *
	 * @return the status of this question entry
	 */
	public int getStatus();

	/**
	 * Sets the status of this question entry.
	 *
	 * @param status the status of this question entry
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.vietnamobile.model.QuestionEntry questionEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.vietnamobile.model.QuestionEntry> toCacheModel();

	@Override
	public com.vietnamobile.model.QuestionEntry toEscapedModel();

	@Override
	public com.vietnamobile.model.QuestionEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}