/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vietnamobile.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VnmOnlintestReportEntry service. Represents a row in the &quot;iskools_VnmOnlintestReportEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vietnamobile.model.impl.VnmOnlintestReportEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vietnamobile.model.impl.VnmOnlintestReportEntryImpl}.
 * </p>
 *
 * @author duymb
 * @see VnmOnlintestReportEntry
 * @see com.vietnamobile.model.impl.VnmOnlintestReportEntryImpl
 * @see com.vietnamobile.model.impl.VnmOnlintestReportEntryModelImpl
 * @generated
 */
public interface VnmOnlintestReportEntryModel extends BaseModel<VnmOnlintestReportEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vnm onlintest report entry model instance should use the {@link VnmOnlintestReportEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this vnm onlintest report entry.
	 *
	 * @return the primary key of this vnm onlintest report entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vnm onlintest report entry.
	 *
	 * @param primaryKey the primary key of this vnm onlintest report entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the vnm onlintest report entry ID of this vnm onlintest report entry.
	 *
	 * @return the vnm onlintest report entry ID of this vnm onlintest report entry
	 */
	public long getVnmOnlintestReportEntryId();

	/**
	 * Sets the vnm onlintest report entry ID of this vnm onlintest report entry.
	 *
	 * @param vnmOnlintestReportEntryId the vnm onlintest report entry ID of this vnm onlintest report entry
	 */
	public void setVnmOnlintestReportEntryId(long vnmOnlintestReportEntryId);

	/**
	 * Returns the group ID of this vnm onlintest report entry.
	 *
	 * @return the group ID of this vnm onlintest report entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this vnm onlintest report entry.
	 *
	 * @param groupId the group ID of this vnm onlintest report entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this vnm onlintest report entry.
	 *
	 * @return the company ID of this vnm onlintest report entry
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this vnm onlintest report entry.
	 *
	 * @param companyId the company ID of this vnm onlintest report entry
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this vnm onlintest report entry.
	 *
	 * @return the create date of this vnm onlintest report entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this vnm onlintest report entry.
	 *
	 * @param createDate the create date of this vnm onlintest report entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this vnm onlintest report entry.
	 *
	 * @return the modified date of this vnm onlintest report entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vnm onlintest report entry.
	 *
	 * @param modifiedDate the modified date of this vnm onlintest report entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the onlinetest entry ID of this vnm onlintest report entry.
	 *
	 * @return the onlinetest entry ID of this vnm onlintest report entry
	 */
	public long getOnlinetestEntryId();

	/**
	 * Sets the onlinetest entry ID of this vnm onlintest report entry.
	 *
	 * @param onlinetestEntryId the onlinetest entry ID of this vnm onlintest report entry
	 */
	public void setOnlinetestEntryId(long onlinetestEntryId);

	/**
	 * Returns the question entry ID of this vnm onlintest report entry.
	 *
	 * @return the question entry ID of this vnm onlintest report entry
	 */
	public long getQuestionEntryId();

	/**
	 * Sets the question entry ID of this vnm onlintest report entry.
	 *
	 * @param questionEntryId the question entry ID of this vnm onlintest report entry
	 */
	public void setQuestionEntryId(long questionEntryId);

	/**
	 * Returns the correct time of this vnm onlintest report entry.
	 *
	 * @return the correct time of this vnm onlintest report entry
	 */
	public int getCorrectTime();

	/**
	 * Sets the correct time of this vnm onlintest report entry.
	 *
	 * @param correctTime the correct time of this vnm onlintest report entry
	 */
	public void setCorrectTime(int correctTime);

	/**
	 * Returns the wrong time of this vnm onlintest report entry.
	 *
	 * @return the wrong time of this vnm onlintest report entry
	 */
	public int getWrongTime();

	/**
	 * Sets the wrong time of this vnm onlintest report entry.
	 *
	 * @param wrongTime the wrong time of this vnm onlintest report entry
	 */
	public void setWrongTime(int wrongTime);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.vietnamobile.model.VnmOnlintestReportEntry vnmOnlintestReportEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.vietnamobile.model.VnmOnlintestReportEntry> toCacheModel();

	@Override
	public com.vietnamobile.model.VnmOnlintestReportEntry toEscapedModel();

	@Override
	public com.vietnamobile.model.VnmOnlintestReportEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}